export const states = [
  { fullName: "Alabama", abbrevCode: "AL" },
  { fullName: "Alaska", abbrevCode: "AK" },
  { fullName: "Arizona", abbrevCode: "AZ" },
  { fullName: "Arkansas", abbrevCode: "AR" },
  { fullName: "California", abbrevCode: "CA" },
  { fullName: "Colorado", abbrevCode: "CO" },
  { fullName: "Connecticut", abbrevCode: "CT" },
  { fullName: "Delaware", abbrevCode: "DE" },
  { fullName: "District of Columbia", abbrevCode: "DC" },
  { fullName: "Florida", abbrevCode: "FL" },
  { fullName: "Georgia", abbrevCode: "GA" },
  { fullName: "Hawaii", abbrevCode: "HI" },
  { fullName: "Idaho", abbrevCode: "ID" },
  { fullName: "Illinois", abbrevCode: "IL" },
  { fullName: "Indiana", abbrevCode: "IN" },
  { fullName: "Iowa", abbrevCode: "IA" },
  { fullName: "Kansas", abbrevCode: "KS" },
  { fullName: "Kentucky", abbrevCode: "KY" },
  { fullName: "Louisiana", abbrevCode: "LA" },
  { fullName: "Maine", abbrevCode: "ME" },
  { fullName: "Maryland", abbrevCode: "MD" },
  { fullName: "Massachusetts", abbrevCode: "MA" },
  { fullName: "Michigan", abbrevCode: "MI" },
  { fullName: "Minnesota", abbrevCode: "MN" },
  { fullName: "Mississippi", abbrevCode: "MS" },
  { fullName: "Missouri", abbrevCode: "MO" },
  { fullName: "Montana", abbrevCode: "MT" },
  { fullName: "Nebraska", abbrevCode: "NE" },
  { fullName: "Nevada", abbrevCode: "NV" },
  { fullName: "New Hampshire", abbrevCode: "NH" },
  { fullName: "New Jersey", abbrevCode: "NJ" },
  { fullName: "New Mexico", abbrevCode: "NM" },
  { fullName: "New York", abbrevCode: "NY" },
  { fullName: "North Carolina", abbrevCode: "NC" },
  { fullName: "North Dakota", abbrevCode: "ND" },
  { fullName: "Ohio", abbrevCode: "OH" },
  { fullName: "Oklahoma", abbrevCode: "OK" },
  { fullName: "Oregon", abbrevCode: "OR" },
  { fullName: "Pennsylvania", abbrevCode: "PA" },
  { fullName: "Rhode Island", abbrevCode: "RI" },
  { fullName: "South Carolina", abbrevCode: "SC" },
  { fullName: "South Dakota", abbrevCode: "SD" },
  { fullName: "Tennessee", abbrevCode: "TN" },
  { fullName: "Texas", abbrevCode: "TX" },
  { fullName: "Utah", abbrevCode: "UT" },
  { fullName: "Vermont", abbrevCode: "VT" },
  { fullName: "Virginia", abbrevCode: "VA" },
  { fullName: "Washington", abbrevCode: "WA" },
  { fullName: "West Virginia", abbrevCode: "WV" },
  { fullName: "Wisconsin", abbrevCode: "WI" },
  { fullName: "Wyoming", abbrevCode: "WY" },
];
